name: Setup
description: install dependencies and build

inputs:
  extra_filters:
    description: 'Turbo additional filters to select packages to build'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10.12.4

    - uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        check-latest: true

    - name: Install dependencies
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: |
        if pnpm i --frozen-lockfile; then
          echo "Lockfile is compatible"
        else
          echo "Lockfile incompatible, regenerating..."
          pnpm i --no-frozen-lockfile
        fi

    - name: Build
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: pnpm build ${{ inputs.extra_filters }}