name: Deploy Integrations
description: Deploy integrations to Botpress

inputs:
  environment:
    description: "Environment to deploy to production"
    required: true
  force:
    description: "Force re-deploying integrations"
    required: false
    default: "false"
  token_pat:
    description: "Botpress token for plus account"
    required: true
  plus_workspace_id:
    description: "Botpress workspace ID for plus"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Botpress
      shell: bash
      run: |
        pnpm bp login -y --token ${{ inputs.token_pat }} --workspace-id ${{ inputs.plus_workspace_id }}

    - name: Deploy integrations
      shell: bash
      run: |
        # Get list of integration directories
        cd integrations
        for integration in */; do
          if [ -d "$integration" ]; then
            integration_name=${integration%/}
            exists=$(./.github/scripts/integration-exists.sh $integration)
            
            # Only deploy if integration doesn't exist or force is enabled
            if [ "$exists" = "0" ] || [ "${{ inputs.force }}" = "true" ]; then
              echo "Deploying integration: $integration_name"
              
              cd "$integration_name"
              
              # Build the integration
              echo "Building $integration_name..."
              pnpm exec bp build
              
              # Deploy the integration
              echo "Deploying $integration_name..."
              if [ "${{ inputs.force }}" = "true" ]; then
                pnpm exec bp deploy --force --public
              else
                pnpm exec bp deploy --public
              fi
              
              cd ..
            else
              echo "Integration $integration_name already exists, skipping deployment (use force=true to override)"
            fi
          fi
        done

        echo "Deployment completed successfully"
