name: Deploy Integrations

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      force:
        description: "Force re-deploying integrations"
        type: boolean
        required: false
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && (contains(toJSON(github.event.head_commit.modified), 'integrations/') || contains(toJSON(github.event.head_commit.added), 'integrations/'))) || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Deploy Integrations
        uses: ./.github/actions/deploy-integrations
        with:
          force: ${{ github.event.inputs.force || 'false' }}
          token_pat: ${{ secrets.PRODUCTION_TOKEN_CLOUD_OPS_ACCOUNT }}
          plus_workspace_id: ${{ secrets.BP_WORKSPACEID_PROD }}
          botpress_workspace_id: ${{ secrets.GLOBAL_BP_WORKSPACE_ID }}
