name: Deploy Integrations Production

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force re-deploying integrations'
        type: boolean
        required: false
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy-production:
    runs-on: depot-ubuntu-22.04-8
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - name: Deploy Interfaces
        uses: ./.github/actions/deploy-interfaces
        with:
          environment: 'production'
          force: ${{ github.event.inputs.force == 'true' }}
          token_cloud_ops_account: ${{ secrets.ERMEK_PROD_PAT }}
          cloud_ops_workspace_id: ${{ secrets.BP_WORKSPACEID_PROD }}
      - name: Deploy Integrations
        uses: ./.github/actions/deploy-integrations
        with:
          environment: 'production'
          force: ${{ github.event.inputs.force == 'true' }}
          token_cloud_ops_account: ${{ secrets.ERMEK_PROD_PAT }}
          cloud_ops_workspace_id: ${{ secrets.BP_WORKSPACEID_PROD }}
      - name: Deploy Plugins
        uses: ./.github/actions/deploy-plugins
        with:
          environment: 'production'
          force: ${{ github.event.inputs.force == 'true' }}
          token_cloud_ops_account: ${{ secrets.ERMEK_PROD_PAT }}
          cloud_ops_workspace_id: ${{ secrets.BP_WORKSPACEID_PROD }}