name: Deploy Integrations Production

on:
  push:
    branches:
      - master
    paths:
      - 'integrations/**'
  workflow_dispatch:
    inputs:
      force:
        description: 'Force re-deploying integrations'
        type: boolean
        required: false
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Deploy Integrations
        uses: ./.github/actions/deploy-integrations
        with:
          force: ${{ github.event.inputs.force || 'false' }}
          token_pat: ${{ secrets.PRODUCTION_TOKEN_CLOUD_OPS_ACCOUNT }}
          plus_workspace_id: ${{ secrets.BP_WORKSPACEID_PROD }}
          botpress_workspace_id: ${{ secrets.GLOBAL_BP_WORKSPACE_ID }}
