name: Deploy Bots

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - name: Deploy Bots
        env:
          PRODUCTION_CLOUD_OPS_WORKSPACE_ID: ${{ secrets.BP_WORKSPACEID_PROD }}
          PRODUCTION_TOKEN_CLOUD_OPS_ACCOUNT: ${{ secrets.ERMEK_PROD_PAT }}
        run: |
          api_url="https://api.botpress.cloud"

          # login
          echo "### Logging in to $api_url ###"
          pnpm bp login -y --api-url $api_url --workspaceId "${{ secrets.BP_WORKSPACEID_PROD }}" --token "${{ secrets.ERMEK_PROD_PAT }}"

          # deploy
          # Find all bot directories (adjust the filter as needed based on your project structure)
          bots="pnpm list --json"
          bot_paths=$(eval $bots | jq -r "map(.path) | .[]")

          for bot_path in $bot_paths; do
              bot_name=$(basename $bot_path)
              echo -e "\nDeploying bot: ### $bot_name ###\n"
              bot_id=$(pnpm bp bots new --name $bot_name --json --if-not-exists | jq -r ".id")
              pnpm retry -n 2 -- pnpm -F $bot_name -c exec -- "pnpm bp deploy -v -y --botId $bot_id"
          done