name: Code Styling

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Prettier check
        id: prettier
        run: pnpm exec prettier --check .
        continue-on-error: true

      - name: Run ESLint check
        id: eslint
        run: pnpm run lint
        continue-on-error: true

      - name: Fail job if any checks failed
        if: steps.prettier.outcome == 'failure' || steps.eslint.outcome == 'failure'
        run: |
          if [[ "${{ steps.prettier.outcome }}" == "failure" ]]; then
            echo "❌ Prettier Check Failed: Some files are not properly formatted. Please run 'pnpm exec prettier --write .' to fix formatting issues."
          fi
          if [[ "${{ steps.eslint.outcome }}" == "failure" ]]; then
            echo "❌ ESLint Check Failed: ESLint found code quality issues. Please run 'pnpm run lint' to see the issues and fix them."
          fi
          exit 1