name: Test Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force re-deploying integrations"
        type: boolean
        required: false
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  test-deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test Deployment Workflow
        uses: ./.github/actions/test-deployment
        with:
          force: ${{ github.event.inputs.force || 'false' }}
          token_pat: ${{ secrets.PRODUCTION_TOKEN_CLOUD_OPS_ACCOUNT }}
          plus_workspace_id: ${{ secrets.BP_WORKSPACEID_PROD }}
          botpress_workspace_id: ${{ secrets.GLOBAL_BP_WORKSPACE_ID }}
